
// This file has been generated by the GUI designer. Do not modify.
namespace iMetaGui
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.VBox vbox2;
		private global::Gtk.VBox vbox1;
		private global::iMetaGui.TopBar topbar;
		private global::Gtk.Notebook notebook1;
		private global::iMetaGui.MovieListGui guiMovieList;
		private global::Gtk.Label label3;
		private global::Gtk.VBox vboxTvShows;
		private global::Gtk.Notebook nbkTvShows;
		private global::iMetaGui.TvShowListGui guiTvShowList;
		private global::Gtk.Label label10;
		private global::iMetaGui.TvShowGui guiTvShow;
		private global::Gtk.Label label11;
		private global::Gtk.Label label6;
		private global::Gtk.ScrolledWindow scrolledwindow4;
		private global::Gtk.TextView txtLog;
		private global::Gtk.Label lblLog;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget iMetaGui.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "iMetaGui.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("iMeta");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.iMeta.ico");
			// Container child iMetaGui.MainWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.topbar = new global::iMetaGui.TopBar ();
			this.topbar.HeightRequest = 85;
			this.topbar.Events = ((global::Gdk.EventMask)(256));
			this.topbar.Name = "topbar";
			this.topbar.IsStatusPulsing = false;
			this.topbar.TvShowsButtonIsActive = false;
			this.topbar.MoviesButtonIsActive = false;
			this.vbox1.Add (this.topbar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.topbar]));
			w2.Position = 0;
			w2.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			this.notebook1.ShowBorder = false;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.guiMovieList = new global::iMetaGui.MovieListGui ();
			this.guiMovieList.Events = ((global::Gdk.EventMask)(256));
			this.guiMovieList.Name = "guiMovieList";
			this.notebook1.Add (this.guiMovieList);
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.WidthRequest = 100;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Movies");
			this.notebook1.SetTabLabel (this.guiMovieList, this.label3);
			this.label3.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vboxTvShows = new global::Gtk.VBox ();
			this.vboxTvShows.Name = "vboxTvShows";
			// Container child vboxTvShows.Gtk.Box+BoxChild
			this.nbkTvShows = new global::Gtk.Notebook ();
			this.nbkTvShows.CanFocus = true;
			this.nbkTvShows.Name = "nbkTvShows";
			this.nbkTvShows.CurrentPage = 0;
			// Container child nbkTvShows.Gtk.Notebook+NotebookChild
			this.guiTvShowList = new global::iMetaGui.TvShowListGui ();
			this.guiTvShowList.Events = ((global::Gdk.EventMask)(256));
			this.guiTvShowList.Name = "guiTvShowList";
			this.nbkTvShows.Add (this.guiTvShowList);
			// Notebook tab
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
			this.nbkTvShows.SetTabLabel (this.guiTvShowList, this.label10);
			this.label10.ShowAll ();
			// Container child nbkTvShows.Gtk.Notebook+NotebookChild
			this.guiTvShow = new global::iMetaGui.TvShowGui ();
			this.guiTvShow.Events = ((global::Gdk.EventMask)(256));
			this.guiTvShow.Name = "guiTvShow";
			this.nbkTvShows.Add (this.guiTvShow);
			global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.nbkTvShows [this.guiTvShow]));
			w5.Position = 1;
			// Notebook tab
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
			this.nbkTvShows.SetTabLabel (this.guiTvShow, this.label11);
			this.label11.ShowAll ();
			this.vboxTvShows.Add (this.nbkTvShows);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxTvShows [this.nbkTvShows]));
			w6.Position = 0;
			this.notebook1.Add (this.vboxTvShows);
			global::Gtk.Notebook.NotebookChild w7 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vboxTvShows]));
			w7.Position = 1;
			// Notebook tab
			this.label6 = new global::Gtk.Label ();
			this.label6.WidthRequest = 100;
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("TV Shows");
			this.notebook1.SetTabLabel (this.vboxTvShows, this.label6);
			this.label6.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.scrolledwindow4 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow4.CanFocus = true;
			this.scrolledwindow4.Name = "scrolledwindow4";
			this.scrolledwindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow4.Gtk.Container+ContainerChild
			this.txtLog = new global::Gtk.TextView ();
			this.txtLog.CanFocus = true;
			this.txtLog.Name = "txtLog";
			this.scrolledwindow4.Add (this.txtLog);
			this.notebook1.Add (this.scrolledwindow4);
			global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.scrolledwindow4]));
			w9.Position = 2;
			// Notebook tab
			this.lblLog = new global::Gtk.Label ();
			this.lblLog.WidthRequest = 100;
			this.lblLog.Name = "lblLog";
			this.lblLog.LabelProp = global::Mono.Unix.Catalog.GetString ("Log");
			this.notebook1.SetTabLabel (this.scrolledwindow4, this.lblLog);
			this.lblLog.ShowAll ();
			this.vbox1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
			w10.Position = 1;
			this.vbox2.Add (this.vbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox1]));
			w11.Position = 0;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1226;
			this.DefaultHeight = 820;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
