
// This file has been generated by the GUI designer. Do not modify.
namespace iMetaGui
{
	public partial class MenuButton
	{
		private global::Gtk.EventBox eventbox2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget iMetaGui.MenuButton
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 28;
			this.HeightRequest = 22;
			this.Name = "iMetaGui.MenuButton";
			// Container child iMetaGui.MenuButton.Gtk.Container+ContainerChild
			this.eventbox2 = new global::Gtk.EventBox ();
			this.eventbox2.WidthRequest = 28;
			this.eventbox2.HeightRequest = 22;
			this.eventbox2.Name = "eventbox2";
			this.Add (this.eventbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
