
// This file has been generated by the GUI designer. Do not modify.
namespace iMetaGui
{
	public partial class RatingWidget
	{
		private global::Gtk.Table table1;
		private global::Gtk.EventBox eventbox1;
		private global::Gtk.Image image1;
		private global::Gtk.EventBox eventbox10;
		private global::Gtk.Image image10;
		private global::Gtk.EventBox eventbox2;
		private global::Gtk.Image image2;
		private global::Gtk.EventBox eventbox3;
		private global::Gtk.Image image3;
		private global::Gtk.EventBox eventbox4;
		private global::Gtk.Image image4;
		private global::Gtk.EventBox eventbox5;
		private global::Gtk.Image image5;
		private global::Gtk.EventBox eventbox6;
		private global::Gtk.Image image6;
		private global::Gtk.EventBox eventbox7;
		private global::Gtk.Image image7;
		private global::Gtk.EventBox eventbox8;
		private global::Gtk.Image image8;
		private global::Gtk.EventBox eventbox9;
		private global::Gtk.Image image9;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget iMetaGui.RatingWidget
			global::Stetic.BinContainer.Attach (this);
			this.HeightRequest = 32;
			this.Name = "iMetaGui.RatingWidget";
			// Container child iMetaGui.RatingWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(10)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.star32.png");
			this.eventbox1.Add (this.image1);
			this.table1.Add (this.eventbox1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.eventbox1]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.eventbox10 = new global::Gtk.EventBox ();
			this.eventbox10.Name = "eventbox10";
			// Container child eventbox10.Gtk.Container+ContainerChild
			this.image10 = new global::Gtk.Image ();
			this.image10.Name = "image10";
			this.image10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.starempty32.png");
			this.eventbox10.Add (this.image10);
			this.table1.Add (this.eventbox10);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.eventbox10]));
			w4.LeftAttach = ((uint)(9));
			w4.RightAttach = ((uint)(10));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.eventbox2 = new global::Gtk.EventBox ();
			this.eventbox2.Name = "eventbox2";
			// Container child eventbox2.Gtk.Container+ContainerChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.star32.png");
			this.eventbox2.Add (this.image2);
			this.table1.Add (this.eventbox2);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.eventbox2]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.eventbox3 = new global::Gtk.EventBox ();
			this.eventbox3.Name = "eventbox3";
			// Container child eventbox3.Gtk.Container+ContainerChild
			this.image3 = new global::Gtk.Image ();
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.star32.png");
			this.eventbox3.Add (this.image3);
			this.table1.Add (this.eventbox3);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.eventbox3]));
			w8.LeftAttach = ((uint)(2));
			w8.RightAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.eventbox4 = new global::Gtk.EventBox ();
			this.eventbox4.Name = "eventbox4";
			// Container child eventbox4.Gtk.Container+ContainerChild
			this.image4 = new global::Gtk.Image ();
			this.image4.Name = "image4";
			this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.star32.png");
			this.eventbox4.Add (this.image4);
			this.table1.Add (this.eventbox4);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.eventbox4]));
			w10.LeftAttach = ((uint)(3));
			w10.RightAttach = ((uint)(4));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.eventbox5 = new global::Gtk.EventBox ();
			this.eventbox5.Name = "eventbox5";
			// Container child eventbox5.Gtk.Container+ContainerChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.star32.png");
			this.eventbox5.Add (this.image5);
			this.table1.Add (this.eventbox5);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.eventbox5]));
			w12.LeftAttach = ((uint)(4));
			w12.RightAttach = ((uint)(5));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.eventbox6 = new global::Gtk.EventBox ();
			this.eventbox6.Name = "eventbox6";
			// Container child eventbox6.Gtk.Container+ContainerChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.starempty32.png");
			this.eventbox6.Add (this.image6);
			this.table1.Add (this.eventbox6);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.eventbox6]));
			w14.LeftAttach = ((uint)(5));
			w14.RightAttach = ((uint)(6));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.eventbox7 = new global::Gtk.EventBox ();
			this.eventbox7.Name = "eventbox7";
			// Container child eventbox7.Gtk.Container+ContainerChild
			this.image7 = new global::Gtk.Image ();
			this.image7.Name = "image7";
			this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.starempty32.png");
			this.eventbox7.Add (this.image7);
			this.table1.Add (this.eventbox7);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.eventbox7]));
			w16.LeftAttach = ((uint)(6));
			w16.RightAttach = ((uint)(7));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.eventbox8 = new global::Gtk.EventBox ();
			this.eventbox8.Name = "eventbox8";
			// Container child eventbox8.Gtk.Container+ContainerChild
			this.image8 = new global::Gtk.Image ();
			this.image8.Name = "image8";
			this.image8.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.starempty32.png");
			this.eventbox8.Add (this.image8);
			this.table1.Add (this.eventbox8);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.eventbox8]));
			w18.LeftAttach = ((uint)(7));
			w18.RightAttach = ((uint)(8));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.eventbox9 = new global::Gtk.EventBox ();
			this.eventbox9.Name = "eventbox9";
			// Container child eventbox9.Gtk.Container+ContainerChild
			this.image9 = new global::Gtk.Image ();
			this.image9.Name = "image9";
			this.image9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.starempty32.png");
			this.eventbox9.Add (this.image9);
			this.table1.Add (this.eventbox9);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.eventbox9]));
			w20.LeftAttach = ((uint)(8));
			w20.RightAttach = ((uint)(9));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
