
// This file has been generated by the GUI designer. Do not modify.
namespace iMetaGui
{
	public partial class TvShowListGui
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.IconView iconview1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget iMetaGui.TvShowListGui
			global::Stetic.BinContainer.Attach (this);
			this.Name = "iMetaGui.TvShowListGui";
			// Container child iMetaGui.TvShowListGui.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.iconview1 = new global::Gtk.IconView ();
			this.iconview1.CanFocus = true;
			this.iconview1.Name = "iconview1";
			this.scrolledwindow1.Add (this.iconview1);
			this.Add (this.scrolledwindow1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
