
// This file has been generated by the GUI designer. Do not modify.
namespace iMetaGui
{
	public partial class WindowsButtons
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.EventBox eventMinimize;
		private global::Gtk.EventBox eventMaximize;
		private global::Gtk.EventBox eventClose;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget iMetaGui.WindowsButtons
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 95;
			this.HeightRequest = 18;
			this.Name = "iMetaGui.WindowsButtons";
			// Container child iMetaGui.WindowsButtons.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.eventMinimize = new global::Gtk.EventBox ();
			this.eventMinimize.WidthRequest = 26;
			this.eventMinimize.HeightRequest = 18;
			this.eventMinimize.Name = "eventMinimize";
			this.fixed1.Add (this.eventMinimize);
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.eventMaximize = new global::Gtk.EventBox ();
			this.eventMaximize.WidthRequest = 26;
			this.eventMaximize.HeightRequest = 18;
			this.eventMaximize.Name = "eventMaximize";
			this.fixed1.Add (this.eventMaximize);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.eventMaximize]));
			w2.X = 26;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.eventClose = new global::Gtk.EventBox ();
			this.eventClose.WidthRequest = 43;
			this.eventClose.HeightRequest = 18;
			this.eventClose.Name = "eventClose";
			this.fixed1.Add (this.eventClose);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.eventClose]));
			w3.X = 52;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
