
// This file has been generated by the GUI designer. Do not modify.
namespace iMetaGui
{
	public partial class StatusWidget
	{
		private global::Gtk.EventBox eventbox1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget iMetaGui.StatusWidget
			global::Stetic.BinContainer.Attach (this);
			this.HeightRequest = 48;
			this.Name = "iMetaGui.StatusWidget";
			// Container child iMetaGui.StatusWidget.Gtk.Container+ContainerChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.Name = "eventbox1";
			this.Add (this.eventbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
