
// This file has been generated by the GUI designer. Do not modify.
namespace iMetaGui
{
	public partial class PreferencesDialog
	{
		private global::Gtk.Table table1;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.Notebook notebook1;
		private global::Gtk.Table table2;
		private global::Gtk.FileChooserButton fcbCachePath;
		private global::Gtk.Fixed fixed3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView nvVideoExtensions;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button btnAddVideoExtension;
		private global::Gtk.Button btnRemoveVideoExtension;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.Label label1;
		private global::Gtk.Label lblCachePathDescription;
		private global::Gtk.Label label5;
		private global::Gtk.Table table3;
		private global::Gtk.CheckButton chkAddYearToMovieFolders;
		private global::Gtk.CheckButton chkAttempToDownloadTrailers;
		private global::Gtk.CheckButton chkAttemptToDownloadMissingTrailers;
		private global::Gtk.CheckButton chkUseFolderNameForMovieLookup;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.NodeView nvMovieFolders;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Button btnMovieFolderAdd;
		private global::Gtk.Button btnMovieFolderRemove;
		private global::Gtk.HSeparator hseparator4;
		private global::Gtk.Label label4;
		private global::Gtk.Label label6;
		private global::Gtk.SpinButton numMaxFanArt;
		private global::Gtk.Label label2;
		private global::Gtk.Table table4;
		private global::Gtk.CheckButton chkAutoRenameEpisodes;
		private global::Gtk.CheckButton chkUseBannersForFolderImage;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.NodeView nvTvFolders;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button btnTvFolderAdd;
		private global::Gtk.Button btnTvFolderRemove;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.HSeparator hseparator5;
		private global::Gtk.Label label8;
		private global::Gtk.Label lblAutoRenameDescription;
		private global::Gtk.Label label3;
		private global::Gtk.Table table5;
		private global::Gtk.Label label10;
		private global::Gtk.Label label11;
		private global::Gtk.Label label12;
		private global::Gtk.Label label13;
		private global::Gtk.Label label14;
		private global::Gtk.Label label15;
		private global::Gtk.Label label16;
		private global::Gtk.Label label17;
		private global::Gtk.Label lblTvRegexDescription1;
		private global::Gtk.Entry txtBannerResolution;
		private global::Gtk.Entry txtFanArtResolution;
		private global::Gtk.Entry txtImageQuality;
		private global::Gtk.Entry txtPosterResolution;
		private global::Gtk.Entry txtTvEpisodeNumbersRegex;
		private global::Gtk.Entry txtTvRegex;
		private global::Gtk.Entry txtTvSeasonRegex;
		private global::Gtk.Entry txtTvShowTitleRegex;
		private global::Gtk.Label label9;
		private global::Gtk.Table tblTabs;
		private global::Gtk.EventBox eventTabAdvanced;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Image image21;
		private global::Gtk.Label lblTabAdvanced;
		private global::Gtk.EventBox eventTabGeneral;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Image image14;
		private global::Gtk.Label lblTabGeneral;
		private global::Gtk.EventBox eventTabMovies;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Image image15;
		private global::Gtk.Label lblTabMovies;
		private global::Gtk.EventBox eventTabTvShows;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Image image16;
		private global::Gtk.Label lblTabTvShows;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget iMetaGui.PreferencesDialog
			this.Name = "iMetaGui.PreferencesDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Preferences");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Internal child iMetaGui.PreferencesDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(5)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(7));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.table1.Add (this.hseparator2);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.hseparator2]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.RightAttach = ((uint)(5));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 2;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table2 = new global::Gtk.Table (((uint)(5)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.fcbCachePath = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select A File"), ((global::Gtk.FileChooserAction)(2)));
			this.fcbCachePath.WidthRequest = 300;
			this.fcbCachePath.Name = "fcbCachePath";
			this.table2.Add (this.fcbCachePath);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.fcbCachePath]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.WidthRequest = 80;
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.table2.Add (this.fixed3);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed3]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nvVideoExtensions = new global::Gtk.NodeView ();
			this.nvVideoExtensions.HeightRequest = 150;
			this.nvVideoExtensions.CanFocus = true;
			this.nvVideoExtensions.Name = "nvVideoExtensions";
			this.GtkScrolledWindow.Add (this.nvVideoExtensions);
			this.table2.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.GtkScrolledWindow]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnAddVideoExtension = new global::Gtk.Button ();
			this.btnAddVideoExtension.CanFocus = true;
			this.btnAddVideoExtension.Name = "btnAddVideoExtension";
			this.btnAddVideoExtension.UseStock = true;
			this.btnAddVideoExtension.UseUnderline = true;
			this.btnAddVideoExtension.Label = "gtk-add";
			this.hbox1.Add (this.btnAddVideoExtension);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnAddVideoExtension]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnRemoveVideoExtension = new global::Gtk.Button ();
			this.btnRemoveVideoExtension.CanFocus = true;
			this.btnRemoveVideoExtension.Name = "btnRemoveVideoExtension";
			this.btnRemoveVideoExtension.UseStock = true;
			this.btnRemoveVideoExtension.UseUnderline = true;
			this.btnRemoveVideoExtension.Label = "gtk-remove";
			this.hbox1.Add (this.btnRemoveVideoExtension);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnRemoveVideoExtension]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.table2.Add (this.hbox1);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox1]));
			w9.TopAttach = ((uint)(4));
			w9.BottomAttach = ((uint)(5));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.table2.Add (this.hseparator1);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.hseparator1]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Cache Path:");
			this.table2.Add (this.label1);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lblCachePathDescription = new global::Gtk.Label ();
			this.lblCachePathDescription.WidthRequest = 426;
			this.lblCachePathDescription.Name = "lblCachePathDescription";
			this.lblCachePathDescription.Xalign = 0F;
			this.lblCachePathDescription.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\"small\">This is the path all temporary files will be saved to, this is" +
				" used to reduce internet traffic.</span>"
			);
			this.lblCachePathDescription.UseMarkup = true;
			this.lblCachePathDescription.Wrap = true;
			this.table2.Add (this.lblCachePathDescription);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.lblCachePathDescription]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table2);
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
			this.notebook1.SetTabLabel (this.table2, this.label5);
			this.label5.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table3 = new global::Gtk.Table (((uint)(10)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.chkAddYearToMovieFolders = new global::Gtk.CheckButton ();
			this.chkAddYearToMovieFolders.CanFocus = true;
			this.chkAddYearToMovieFolders.Name = "chkAddYearToMovieFolders";
			this.chkAddYearToMovieFolders.Label = global::Mono.Unix.Catalog.GetString ("Add Year to Movie folders");
			this.chkAddYearToMovieFolders.DrawIndicator = true;
			this.chkAddYearToMovieFolders.UseUnderline = true;
			this.table3.Add (this.chkAddYearToMovieFolders);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3 [this.chkAddYearToMovieFolders]));
			w14.TopAttach = ((uint)(5));
			w14.BottomAttach = ((uint)(6));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.chkAttempToDownloadTrailers = new global::Gtk.CheckButton ();
			this.chkAttempToDownloadTrailers.CanFocus = true;
			this.chkAttempToDownloadTrailers.Name = "chkAttempToDownloadTrailers";
			this.chkAttempToDownloadTrailers.Label = global::Mono.Unix.Catalog.GetString ("Attempt to download trailers");
			this.chkAttempToDownloadTrailers.DrawIndicator = true;
			this.chkAttempToDownloadTrailers.UseUnderline = true;
			this.table3.Add (this.chkAttempToDownloadTrailers);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.chkAttempToDownloadTrailers]));
			w15.TopAttach = ((uint)(6));
			w15.BottomAttach = ((uint)(7));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.chkAttemptToDownloadMissingTrailers = new global::Gtk.CheckButton ();
			this.chkAttemptToDownloadMissingTrailers.CanFocus = true;
			this.chkAttemptToDownloadMissingTrailers.Name = "chkAttemptToDownloadMissingTrailers";
			this.chkAttemptToDownloadMissingTrailers.Label = global::Mono.Unix.Catalog.GetString ("Attempt to download missing trailers");
			this.chkAttemptToDownloadMissingTrailers.DrawIndicator = true;
			this.chkAttemptToDownloadMissingTrailers.UseUnderline = true;
			this.table3.Add (this.chkAttemptToDownloadMissingTrailers);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.chkAttemptToDownloadMissingTrailers]));
			w16.TopAttach = ((uint)(7));
			w16.BottomAttach = ((uint)(8));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.chkUseFolderNameForMovieLookup = new global::Gtk.CheckButton ();
			this.chkUseFolderNameForMovieLookup.CanFocus = true;
			this.chkUseFolderNameForMovieLookup.Name = "chkUseFolderNameForMovieLookup";
			this.chkUseFolderNameForMovieLookup.Label = global::Mono.Unix.Catalog.GetString ("Use Folder name when looking up Movie name");
			this.chkUseFolderNameForMovieLookup.DrawIndicator = true;
			this.chkUseFolderNameForMovieLookup.UseUnderline = true;
			this.table3.Add (this.chkUseFolderNameForMovieLookup);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3 [this.chkUseFolderNameForMovieLookup]));
			w17.TopAttach = ((uint)(4));
			w17.BottomAttach = ((uint)(5));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.WidthRequest = 80;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.table3.Add (this.fixed2);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed2]));
			w18.TopAttach = ((uint)(9));
			w18.BottomAttach = ((uint)(10));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.nvMovieFolders = new global::Gtk.NodeView ();
			this.nvMovieFolders.WidthRequest = 400;
			this.nvMovieFolders.HeightRequest = 120;
			this.nvMovieFolders.CanFocus = true;
			this.nvMovieFolders.Name = "nvMovieFolders";
			this.GtkScrolledWindow1.Add (this.nvMovieFolders);
			this.table3.Add (this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.GtkScrolledWindow1]));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnMovieFolderAdd = new global::Gtk.Button ();
			this.btnMovieFolderAdd.CanFocus = true;
			this.btnMovieFolderAdd.Name = "btnMovieFolderAdd";
			this.btnMovieFolderAdd.UseUnderline = true;
			// Container child btnMovieFolderAdd.Gtk.Container+ContainerChild
			global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w22 = new global::Gtk.HBox ();
			w22.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w22.Add (w23);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w25 = new global::Gtk.Label ();
			w25.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w25.UseUnderline = true;
			w22.Add (w25);
			w21.Add (w22);
			this.btnMovieFolderAdd.Add (w21);
			this.hbox2.Add (this.btnMovieFolderAdd);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnMovieFolderAdd]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnMovieFolderRemove = new global::Gtk.Button ();
			this.btnMovieFolderRemove.CanFocus = true;
			this.btnMovieFolderRemove.Name = "btnMovieFolderRemove";
			this.btnMovieFolderRemove.UseUnderline = true;
			// Container child btnMovieFolderRemove.Gtk.Container+ContainerChild
			global::Gtk.Alignment w30 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w31 = new global::Gtk.HBox ();
			w31.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w32 = new global::Gtk.Image ();
			w32.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w31.Add (w32);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w34 = new global::Gtk.Label ();
			w34.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove");
			w34.UseUnderline = true;
			w31.Add (w34);
			w30.Add (w31);
			this.btnMovieFolderRemove.Add (w30);
			this.hbox2.Add (this.btnMovieFolderRemove);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnMovieFolderRemove]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			this.table3.Add (this.hbox2);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table3 [this.hbox2]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(3));
			w39.LeftAttach = ((uint)(1));
			w39.RightAttach = ((uint)(2));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.table3.Add (this.hseparator4);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table3 [this.hseparator4]));
			w40.TopAttach = ((uint)(3));
			w40.BottomAttach = ((uint)(4));
			w40.RightAttach = ((uint)(3));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.Yalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Folders:");
			this.table3.Add (this.label4);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table3 [this.label4]));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Max Fanart:");
			this.table3.Add (this.label6);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table3 [this.label6]));
			w42.TopAttach = ((uint)(8));
			w42.BottomAttach = ((uint)(9));
			w42.XOptions = ((global::Gtk.AttachOptions)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.numMaxFanArt = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.numMaxFanArt.WidthRequest = 100;
			this.numMaxFanArt.CanFocus = true;
			this.numMaxFanArt.Name = "numMaxFanArt";
			this.numMaxFanArt.Adjustment.PageIncrement = 10D;
			this.numMaxFanArt.ClimbRate = 1D;
			this.numMaxFanArt.Numeric = true;
			this.table3.Add (this.numMaxFanArt);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table3 [this.numMaxFanArt]));
			w43.TopAttach = ((uint)(8));
			w43.BottomAttach = ((uint)(9));
			w43.LeftAttach = ((uint)(1));
			w43.RightAttach = ((uint)(2));
			w43.XOptions = ((global::Gtk.AttachOptions)(6));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table3);
			global::Gtk.Notebook.NotebookChild w44 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.table3]));
			w44.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
			this.notebook1.SetTabLabel (this.table3, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table4 = new global::Gtk.Table (((uint)(8)), ((uint)(3)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.chkAutoRenameEpisodes = new global::Gtk.CheckButton ();
			this.chkAutoRenameEpisodes.CanFocus = true;
			this.chkAutoRenameEpisodes.Name = "chkAutoRenameEpisodes";
			this.chkAutoRenameEpisodes.Label = global::Mono.Unix.Catalog.GetString ("Auto Rename TV Episodes");
			this.chkAutoRenameEpisodes.DrawIndicator = true;
			this.chkAutoRenameEpisodes.UseUnderline = true;
			this.table4.Add (this.chkAutoRenameEpisodes);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table4 [this.chkAutoRenameEpisodes]));
			w45.TopAttach = ((uint)(3));
			w45.BottomAttach = ((uint)(4));
			w45.LeftAttach = ((uint)(1));
			w45.RightAttach = ((uint)(2));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.chkUseBannersForFolderImage = new global::Gtk.CheckButton ();
			this.chkUseBannersForFolderImage.CanFocus = true;
			this.chkUseBannersForFolderImage.Name = "chkUseBannersForFolderImage";
			this.chkUseBannersForFolderImage.Label = global::Mono.Unix.Catalog.GetString ("Use Banner For Folder.jpg");
			this.chkUseBannersForFolderImage.DrawIndicator = true;
			this.chkUseBannersForFolderImage.UseUnderline = true;
			this.table4.Add (this.chkUseBannersForFolderImage);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table4 [this.chkUseBannersForFolderImage]));
			w46.TopAttach = ((uint)(5));
			w46.BottomAttach = ((uint)(6));
			w46.LeftAttach = ((uint)(1));
			w46.RightAttach = ((uint)(2));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.nvTvFolders = new global::Gtk.NodeView ();
			this.nvTvFolders.WidthRequest = 400;
			this.nvTvFolders.HeightRequest = 120;
			this.nvTvFolders.CanFocus = true;
			this.nvTvFolders.Name = "nvTvFolders";
			this.GtkScrolledWindow2.Add (this.nvTvFolders);
			this.table4.Add (this.GtkScrolledWindow2);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table4 [this.GtkScrolledWindow2]));
			w48.LeftAttach = ((uint)(1));
			w48.RightAttach = ((uint)(2));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnTvFolderAdd = new global::Gtk.Button ();
			this.btnTvFolderAdd.CanFocus = true;
			this.btnTvFolderAdd.Name = "btnTvFolderAdd";
			this.btnTvFolderAdd.UseUnderline = true;
			// Container child btnTvFolderAdd.Gtk.Container+ContainerChild
			global::Gtk.Alignment w49 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w50 = new global::Gtk.HBox ();
			w50.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w51 = new global::Gtk.Image ();
			w51.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w50.Add (w51);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w53 = new global::Gtk.Label ();
			w53.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w53.UseUnderline = true;
			w50.Add (w53);
			w49.Add (w50);
			this.btnTvFolderAdd.Add (w49);
			this.hbox3.Add (this.btnTvFolderAdd);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnTvFolderAdd]));
			w57.Position = 0;
			w57.Expand = false;
			w57.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnTvFolderRemove = new global::Gtk.Button ();
			this.btnTvFolderRemove.CanFocus = true;
			this.btnTvFolderRemove.Name = "btnTvFolderRemove";
			this.btnTvFolderRemove.UseUnderline = true;
			// Container child btnTvFolderRemove.Gtk.Container+ContainerChild
			global::Gtk.Alignment w58 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w59 = new global::Gtk.HBox ();
			w59.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w60 = new global::Gtk.Image ();
			w60.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w59.Add (w60);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w62 = new global::Gtk.Label ();
			w62.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove");
			w62.UseUnderline = true;
			w59.Add (w62);
			w58.Add (w59);
			this.btnTvFolderRemove.Add (w58);
			this.hbox3.Add (this.btnTvFolderRemove);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnTvFolderRemove]));
			w66.Position = 1;
			w66.Expand = false;
			w66.Fill = false;
			this.table4.Add (this.hbox3);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table4 [this.hbox3]));
			w67.TopAttach = ((uint)(1));
			w67.BottomAttach = ((uint)(2));
			w67.LeftAttach = ((uint)(1));
			w67.RightAttach = ((uint)(2));
			w67.XOptions = ((global::Gtk.AttachOptions)(4));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.table4.Add (this.hseparator3);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table4 [this.hseparator3]));
			w68.TopAttach = ((uint)(7));
			w68.BottomAttach = ((uint)(8));
			w68.RightAttach = ((uint)(3));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hseparator5 = new global::Gtk.HSeparator ();
			this.hseparator5.Name = "hseparator5";
			this.table4.Add (this.hseparator5);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table4 [this.hseparator5]));
			w69.TopAttach = ((uint)(2));
			w69.BottomAttach = ((uint)(3));
			w69.RightAttach = ((uint)(3));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.Yalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Folders:");
			this.table4.Add (this.label8);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table4 [this.label8]));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.lblAutoRenameDescription = new global::Gtk.Label ();
			this.lblAutoRenameDescription.Name = "lblAutoRenameDescription";
			this.lblAutoRenameDescription.Xpad = 24;
			this.lblAutoRenameDescription.Xalign = 0F;
			this.lblAutoRenameDescription.Yalign = 0F;
			this.lblAutoRenameDescription.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\"small\">Episodes will be renamed automatically to the folllowing forma" +
				"t\n     [Show Title] - [Season]x[EpisodeNumber] - [Episode Name].[extension]\n</sp" +
				"an>"
			);
			this.lblAutoRenameDescription.UseMarkup = true;
			this.table4.Add (this.lblAutoRenameDescription);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table4 [this.lblAutoRenameDescription]));
			w71.TopAttach = ((uint)(4));
			w71.BottomAttach = ((uint)(5));
			w71.LeftAttach = ((uint)(1));
			w71.RightAttach = ((uint)(2));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table4);
			global::Gtk.Notebook.NotebookChild w72 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.table4]));
			w72.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
			this.notebook1.SetTabLabel (this.table4, this.label3);
			this.label3.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table5 = new global::Gtk.Table (((uint)(10)), ((uint)(3)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Regex:");
			this.table5.Add (this.label10);
			global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.table5 [this.label10]));
			w73.XOptions = ((global::Gtk.AttachOptions)(4));
			w73.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Show Title Regex:");
			this.table5.Add (this.label11);
			global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.table5 [this.label11]));
			w74.TopAttach = ((uint)(2));
			w74.BottomAttach = ((uint)(3));
			w74.XOptions = ((global::Gtk.AttachOptions)(4));
			w74.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Season Number Regex:");
			this.table5.Add (this.label12);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table5 [this.label12]));
			w75.TopAttach = ((uint)(3));
			w75.BottomAttach = ((uint)(4));
			w75.XOptions = ((global::Gtk.AttachOptions)(4));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 1F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Episode Numbers Regex:");
			this.table5.Add (this.label13);
			global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.table5 [this.label13]));
			w76.TopAttach = ((uint)(4));
			w76.BottomAttach = ((uint)(5));
			w76.XOptions = ((global::Gtk.AttachOptions)(4));
			w76.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 1F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Poster Resolution:");
			this.table5.Add (this.label14);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table5 [this.label14]));
			w77.TopAttach = ((uint)(5));
			w77.BottomAttach = ((uint)(6));
			w77.XOptions = ((global::Gtk.AttachOptions)(4));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xalign = 1F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Fan Art Resolution:");
			this.table5.Add (this.label15);
			global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.table5 [this.label15]));
			w78.TopAttach = ((uint)(6));
			w78.BottomAttach = ((uint)(7));
			w78.XOptions = ((global::Gtk.AttachOptions)(4));
			w78.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 1F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Image Quality (0-100):");
			this.table5.Add (this.label16);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table5 [this.label16]));
			w79.TopAttach = ((uint)(8));
			w79.BottomAttach = ((uint)(9));
			w79.XOptions = ((global::Gtk.AttachOptions)(4));
			w79.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.Xalign = 1F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Banner Resolution:");
			this.table5.Add (this.label17);
			global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.table5 [this.label17]));
			w80.TopAttach = ((uint)(7));
			w80.BottomAttach = ((uint)(8));
			w80.XOptions = ((global::Gtk.AttachOptions)(4));
			w80.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.lblTvRegexDescription1 = new global::Gtk.Label ();
			this.lblTvRegexDescription1.Name = "lblTvRegexDescription1";
			this.lblTvRegexDescription1.Xpad = 20;
			this.lblTvRegexDescription1.Xalign = 0F;
			this.lblTvRegexDescription1.LabelProp = global::Mono.Unix.Catalog.GetString (@"<span size=""small"">This is intended for advanced users who have a different TV episode naming struture than expected.  Changing this could result in your TV shows not being detected.
If you clear this field and save your preferences it will be restored to the default Regex.
Note: Group 1 of the regex must return the show name, group 2 the season and group 3 the episode number.</span>"
			);
			this.lblTvRegexDescription1.UseMarkup = true;
			this.lblTvRegexDescription1.Wrap = true;
			this.table5.Add (this.lblTvRegexDescription1);
			global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.table5 [this.lblTvRegexDescription1]));
			w81.TopAttach = ((uint)(1));
			w81.BottomAttach = ((uint)(2));
			w81.LeftAttach = ((uint)(1));
			w81.RightAttach = ((uint)(2));
			w81.XOptions = ((global::Gtk.AttachOptions)(4));
			w81.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.txtBannerResolution = new global::Gtk.Entry ();
			this.txtBannerResolution.CanFocus = true;
			this.txtBannerResolution.Name = "txtBannerResolution";
			this.txtBannerResolution.IsEditable = true;
			this.txtBannerResolution.InvisibleChar = '●';
			this.table5.Add (this.txtBannerResolution);
			global::Gtk.Table.TableChild w82 = ((global::Gtk.Table.TableChild)(this.table5 [this.txtBannerResolution]));
			w82.TopAttach = ((uint)(7));
			w82.BottomAttach = ((uint)(8));
			w82.LeftAttach = ((uint)(1));
			w82.RightAttach = ((uint)(2));
			w82.XOptions = ((global::Gtk.AttachOptions)(4));
			w82.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.txtFanArtResolution = new global::Gtk.Entry ();
			this.txtFanArtResolution.CanFocus = true;
			this.txtFanArtResolution.Name = "txtFanArtResolution";
			this.txtFanArtResolution.IsEditable = true;
			this.txtFanArtResolution.InvisibleChar = '●';
			this.table5.Add (this.txtFanArtResolution);
			global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.table5 [this.txtFanArtResolution]));
			w83.TopAttach = ((uint)(6));
			w83.BottomAttach = ((uint)(7));
			w83.LeftAttach = ((uint)(1));
			w83.RightAttach = ((uint)(2));
			w83.XOptions = ((global::Gtk.AttachOptions)(4));
			w83.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.txtImageQuality = new global::Gtk.Entry ();
			this.txtImageQuality.CanFocus = true;
			this.txtImageQuality.Name = "txtImageQuality";
			this.txtImageQuality.IsEditable = true;
			this.txtImageQuality.InvisibleChar = '●';
			this.table5.Add (this.txtImageQuality);
			global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.table5 [this.txtImageQuality]));
			w84.TopAttach = ((uint)(8));
			w84.BottomAttach = ((uint)(9));
			w84.LeftAttach = ((uint)(1));
			w84.RightAttach = ((uint)(2));
			w84.XOptions = ((global::Gtk.AttachOptions)(4));
			w84.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.txtPosterResolution = new global::Gtk.Entry ();
			this.txtPosterResolution.CanFocus = true;
			this.txtPosterResolution.Name = "txtPosterResolution";
			this.txtPosterResolution.IsEditable = true;
			this.txtPosterResolution.InvisibleChar = '●';
			this.table5.Add (this.txtPosterResolution);
			global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.table5 [this.txtPosterResolution]));
			w85.TopAttach = ((uint)(5));
			w85.BottomAttach = ((uint)(6));
			w85.LeftAttach = ((uint)(1));
			w85.RightAttach = ((uint)(2));
			w85.XOptions = ((global::Gtk.AttachOptions)(4));
			w85.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.txtTvEpisodeNumbersRegex = new global::Gtk.Entry ();
			this.txtTvEpisodeNumbersRegex.CanFocus = true;
			this.txtTvEpisodeNumbersRegex.Name = "txtTvEpisodeNumbersRegex";
			this.txtTvEpisodeNumbersRegex.IsEditable = true;
			this.txtTvEpisodeNumbersRegex.InvisibleChar = '●';
			this.table5.Add (this.txtTvEpisodeNumbersRegex);
			global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.table5 [this.txtTvEpisodeNumbersRegex]));
			w86.TopAttach = ((uint)(4));
			w86.BottomAttach = ((uint)(5));
			w86.LeftAttach = ((uint)(1));
			w86.RightAttach = ((uint)(2));
			w86.XOptions = ((global::Gtk.AttachOptions)(4));
			w86.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.txtTvRegex = new global::Gtk.Entry ();
			this.txtTvRegex.CanFocus = true;
			this.txtTvRegex.Name = "txtTvRegex";
			this.txtTvRegex.IsEditable = true;
			this.txtTvRegex.InvisibleChar = '●';
			this.table5.Add (this.txtTvRegex);
			global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.table5 [this.txtTvRegex]));
			w87.LeftAttach = ((uint)(1));
			w87.RightAttach = ((uint)(2));
			w87.XOptions = ((global::Gtk.AttachOptions)(4));
			w87.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.txtTvSeasonRegex = new global::Gtk.Entry ();
			this.txtTvSeasonRegex.CanFocus = true;
			this.txtTvSeasonRegex.Name = "txtTvSeasonRegex";
			this.txtTvSeasonRegex.IsEditable = true;
			this.txtTvSeasonRegex.InvisibleChar = '●';
			this.table5.Add (this.txtTvSeasonRegex);
			global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.table5 [this.txtTvSeasonRegex]));
			w88.TopAttach = ((uint)(3));
			w88.BottomAttach = ((uint)(4));
			w88.LeftAttach = ((uint)(1));
			w88.RightAttach = ((uint)(2));
			w88.XOptions = ((global::Gtk.AttachOptions)(4));
			w88.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.txtTvShowTitleRegex = new global::Gtk.Entry ();
			this.txtTvShowTitleRegex.CanFocus = true;
			this.txtTvShowTitleRegex.Name = "txtTvShowTitleRegex";
			this.txtTvShowTitleRegex.IsEditable = true;
			this.txtTvShowTitleRegex.InvisibleChar = '●';
			this.table5.Add (this.txtTvShowTitleRegex);
			global::Gtk.Table.TableChild w89 = ((global::Gtk.Table.TableChild)(this.table5 [this.txtTvShowTitleRegex]));
			w89.TopAttach = ((uint)(2));
			w89.BottomAttach = ((uint)(3));
			w89.LeftAttach = ((uint)(1));
			w89.RightAttach = ((uint)(2));
			w89.XOptions = ((global::Gtk.AttachOptions)(4));
			w89.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.table5);
			global::Gtk.Notebook.NotebookChild w90 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.table5]));
			w90.Position = 3;
			// Notebook tab
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("page4");
			this.notebook1.SetTabLabel (this.table5, this.label9);
			this.label9.ShowAll ();
			this.table1.Add (this.notebook1);
			global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.table1 [this.notebook1]));
			w91.TopAttach = ((uint)(2));
			w91.BottomAttach = ((uint)(3));
			w91.LeftAttach = ((uint)(1));
			w91.RightAttach = ((uint)(4));
			w91.XOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.tblTabs = new global::Gtk.Table (((uint)(1)), ((uint)(8)), true);
			this.tblTabs.Name = "tblTabs";
			this.tblTabs.ColumnSpacing = ((uint)(10));
			// Container child tblTabs.Gtk.Table+TableChild
			this.eventTabAdvanced = new global::Gtk.EventBox ();
			this.eventTabAdvanced.Name = "eventTabAdvanced";
			// Container child eventTabAdvanced.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.image21 = new global::Gtk.Image ();
			this.image21.Name = "image21";
			this.image21.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.advanced.png");
			this.vbox5.Add (this.image21);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.image21]));
			w92.Position = 0;
			w92.Expand = false;
			w92.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblTabAdvanced = new global::Gtk.Label ();
			this.lblTabAdvanced.Name = "lblTabAdvanced";
			this.lblTabAdvanced.LabelProp = global::Mono.Unix.Catalog.GetString ("Advanced");
			this.vbox5.Add (this.lblTabAdvanced);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblTabAdvanced]));
			w93.Position = 1;
			w93.Expand = false;
			w93.Fill = false;
			this.eventTabAdvanced.Add (this.vbox5);
			this.tblTabs.Add (this.eventTabAdvanced);
			global::Gtk.Table.TableChild w95 = ((global::Gtk.Table.TableChild)(this.tblTabs [this.eventTabAdvanced]));
			w95.LeftAttach = ((uint)(5));
			w95.RightAttach = ((uint)(6));
			w95.XOptions = ((global::Gtk.AttachOptions)(4));
			w95.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTabs.Gtk.Table+TableChild
			this.eventTabGeneral = new global::Gtk.EventBox ();
			this.eventTabGeneral.Name = "eventTabGeneral";
			// Container child eventTabGeneral.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.image14 = new global::Gtk.Image ();
			this.image14.Name = "image14";
			this.image14.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.generalsettings.png");
			this.vbox2.Add (this.image14);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.image14]));
			w96.Position = 0;
			w96.Expand = false;
			w96.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblTabGeneral = new global::Gtk.Label ();
			this.lblTabGeneral.Name = "lblTabGeneral";
			this.lblTabGeneral.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.vbox2.Add (this.lblTabGeneral);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblTabGeneral]));
			w97.Position = 1;
			w97.Expand = false;
			w97.Fill = false;
			this.eventTabGeneral.Add (this.vbox2);
			this.tblTabs.Add (this.eventTabGeneral);
			global::Gtk.Table.TableChild w99 = ((global::Gtk.Table.TableChild)(this.tblTabs [this.eventTabGeneral]));
			w99.LeftAttach = ((uint)(2));
			w99.RightAttach = ((uint)(3));
			w99.XOptions = ((global::Gtk.AttachOptions)(4));
			w99.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTabs.Gtk.Table+TableChild
			this.eventTabMovies = new global::Gtk.EventBox ();
			this.eventTabMovies.Name = "eventTabMovies";
			// Container child eventTabMovies.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image15 = new global::Gtk.Image ();
			this.image15.Name = "image15";
			this.image15.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.moviesettings.png");
			this.vbox3.Add (this.image15);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.image15]));
			w100.Position = 0;
			w100.Expand = false;
			w100.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblTabMovies = new global::Gtk.Label ();
			this.lblTabMovies.Name = "lblTabMovies";
			this.lblTabMovies.LabelProp = global::Mono.Unix.Catalog.GetString ("Movies");
			this.vbox3.Add (this.lblTabMovies);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblTabMovies]));
			w101.Position = 1;
			w101.Expand = false;
			w101.Fill = false;
			this.eventTabMovies.Add (this.vbox3);
			this.tblTabs.Add (this.eventTabMovies);
			global::Gtk.Table.TableChild w103 = ((global::Gtk.Table.TableChild)(this.tblTabs [this.eventTabMovies]));
			w103.LeftAttach = ((uint)(3));
			w103.RightAttach = ((uint)(4));
			w103.XOptions = ((global::Gtk.AttachOptions)(4));
			w103.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTabs.Gtk.Table+TableChild
			this.eventTabTvShows = new global::Gtk.EventBox ();
			this.eventTabTvShows.Name = "eventTabTvShows";
			// Container child eventTabTvShows.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.image16 = new global::Gtk.Image ();
			this.image16.Name = "image16";
			this.image16.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("iMetaGui.Images.tvsettings.png");
			this.vbox4.Add (this.image16);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.image16]));
			w104.Position = 0;
			w104.Expand = false;
			w104.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.lblTabTvShows = new global::Gtk.Label ();
			this.lblTabTvShows.Name = "lblTabTvShows";
			this.lblTabTvShows.LabelProp = global::Mono.Unix.Catalog.GetString ("TV Shows");
			this.vbox4.Add (this.lblTabTvShows);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblTabTvShows]));
			w105.Position = 1;
			w105.Expand = false;
			w105.Fill = false;
			this.eventTabTvShows.Add (this.vbox4);
			this.tblTabs.Add (this.eventTabTvShows);
			global::Gtk.Table.TableChild w107 = ((global::Gtk.Table.TableChild)(this.tblTabs [this.eventTabTvShows]));
			w107.LeftAttach = ((uint)(4));
			w107.RightAttach = ((uint)(5));
			w107.XOptions = ((global::Gtk.AttachOptions)(4));
			w107.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table1.Add (this.tblTabs);
			global::Gtk.Table.TableChild w108 = ((global::Gtk.Table.TableChild)(this.table1 [this.tblTabs]));
			w108.LeftAttach = ((uint)(1));
			w108.RightAttach = ((uint)(4));
			w108.XOptions = ((global::Gtk.AttachOptions)(0));
			w108.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.table1);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(w1 [this.table1]));
			w109.Position = 0;
			// Internal child iMetaGui.PreferencesDialog.ActionArea
			global::Gtk.HButtonBox w110 = this.ActionArea;
			w110.Name = "dialog1_ActionArea";
			w110.Spacing = 10;
			w110.BorderWidth = ((uint)(5));
			w110.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w111 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w110 [this.buttonCancel]));
			w111.Expand = false;
			w111.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w112 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w110 [this.buttonOk]));
			w112.Position = 1;
			w112.Expand = false;
			w112.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 601;
			this.DefaultHeight = 538;
			this.Show ();
		}
	}
}
