
// This file has been generated by the GUI designer. Do not modify.
namespace iMetaGui
{
	public partial class MacButtons
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.EventBox eventClose;
		private global::Gtk.EventBox eventMaximize;
		private global::Gtk.EventBox eventMinimize;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget iMetaGui.MacButtons
			global::Stetic.BinContainer.Attach (this);
			this.Name = "iMetaGui.MacButtons";
			// Container child iMetaGui.MacButtons.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 60;
			this.fixed1.HeightRequest = 16;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.eventClose = new global::Gtk.EventBox ();
			this.eventClose.WidthRequest = 16;
			this.eventClose.HeightRequest = 16;
			this.eventClose.Name = "eventClose";
			this.fixed1.Add (this.eventClose);
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.eventMaximize = new global::Gtk.EventBox ();
			this.eventMaximize.WidthRequest = 16;
			this.eventMaximize.HeightRequest = 16;
			this.eventMaximize.Name = "eventMaximize";
			this.fixed1.Add (this.eventMaximize);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.eventMaximize]));
			w2.X = 40;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.eventMinimize = new global::Gtk.EventBox ();
			this.eventMinimize.WidthRequest = 16;
			this.eventMinimize.HeightRequest = 16;
			this.eventMinimize.Name = "eventMinimize";
			this.fixed1.Add (this.eventMinimize);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.eventMinimize]));
			w3.X = 20;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
