
// This file has been generated by the GUI designer. Do not modify.
namespace iMetaGui
{
	public partial class iButton
	{
		private global::Gtk.EventBox eventbox1;
		private global::Gtk.Label label1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget iMetaGui.iButton
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 84;
			this.HeightRequest = 22;
			this.Name = "iMetaGui.iButton";
			// Container child iMetaGui.iButton.Gtk.Container+ContainerChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.WidthRequest = 84;
			this.eventbox1.HeightRequest = 22;
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\"x-large\">[Button Text]</span>");
			this.label1.UseMarkup = true;
			this.eventbox1.Add (this.label1);
			this.Add (this.eventbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
