
// This file has been generated by the GUI designer. Do not modify.
namespace iMetaGui
{
	public partial class EpisodeEditorGui
	{
		private global::Gtk.Table table2;
		private global::Gtk.Label Aired;
		private global::Gtk.Label EpisodeName;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView txtPlot;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.NodeView nvActors;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button btnActorsAdd;
		private global::Gtk.Button btnActorsRemove;
		private global::Gtk.Label label10;
		private global::Gtk.Label label11;
		private global::Gtk.Label label12;
		private global::Gtk.Label label13;
		private global::Gtk.Label label14;
		private global::Gtk.Label label15;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Label label7;
		private global::Gtk.Label label8;
		private global::Gtk.Label label9;
		private global::Gtk.SpinButton numDisplayEpisode;
		private global::Gtk.SpinButton numDisplaySeason;
		private global::Gtk.SpinButton numEpisode;
		private global::Gtk.SpinButton numSeason;
		private global::iMetaGui.RatingWidget ratingwidget1;
		private global::Gtk.Entry txtAired;
		private global::Gtk.Entry txtDirectors;
		private global::Gtk.Entry txtEpisodeName;
		private global::Gtk.Entry txtEpisodeStart;
		private global::Gtk.Entry txtMpaa;
		private global::Gtk.Entry txtPremiered;
		private global::Gtk.Entry txtStudio;
		private global::Gtk.Entry txtWriters;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget iMetaGui.EpisodeEditorGui
			global::Stetic.BinContainer.Attach (this);
			this.Name = "iMetaGui.EpisodeEditorGui";
			// Container child iMetaGui.EpisodeEditorGui.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(12)), ((uint)(4)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.Aired = new global::Gtk.Label ();
			this.Aired.Name = "Aired";
			this.Aired.Xpad = 3;
			this.Aired.Xalign = 0F;
			this.Aired.LabelProp = global::Mono.Unix.Catalog.GetString ("Aired:");
			this.table2.Add (this.Aired);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.Aired]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.EpisodeName = new global::Gtk.Label ();
			this.EpisodeName.Name = "EpisodeName";
			this.EpisodeName.Xpad = 3;
			this.EpisodeName.Xalign = 0F;
			this.EpisodeName.LabelProp = global::Mono.Unix.Catalog.GetString ("Episode Name:");
			this.table2.Add (this.EpisodeName);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.EpisodeName]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HeightRequest = 40;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.table2.Add (this.fixed1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed1]));
			w3.TopAttach = ((uint)(11));
			w3.BottomAttach = ((uint)(12));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtPlot = new global::Gtk.TextView ();
			this.txtPlot.HeightRequest = 100;
			this.txtPlot.CanFocus = true;
			this.txtPlot.Name = "txtPlot";
			this.txtPlot.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.txtPlot);
			this.table2.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.GtkScrolledWindow]));
			w5.TopAttach = ((uint)(8));
			w5.BottomAttach = ((uint)(9));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(4));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.HeightRequest = 142;
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.nvActors = new global::Gtk.NodeView ();
			this.nvActors.CanFocus = true;
			this.nvActors.Name = "nvActors";
			this.GtkScrolledWindow1.Add (this.nvActors);
			this.table2.Add (this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.GtkScrolledWindow1]));
			w7.TopAttach = ((uint)(9));
			w7.BottomAttach = ((uint)(10));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(4));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnActorsAdd = new global::Gtk.Button ();
			this.btnActorsAdd.CanFocus = true;
			this.btnActorsAdd.Name = "btnActorsAdd";
			this.btnActorsAdd.UseStock = true;
			this.btnActorsAdd.UseUnderline = true;
			this.btnActorsAdd.Label = "gtk-add";
			this.hbox1.Add (this.btnActorsAdd);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnActorsAdd]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnActorsRemove = new global::Gtk.Button ();
			this.btnActorsRemove.CanFocus = true;
			this.btnActorsRemove.Name = "btnActorsRemove";
			this.btnActorsRemove.UseStock = true;
			this.btnActorsRemove.UseUnderline = true;
			this.btnActorsRemove.Label = "gtk-remove";
			this.hbox1.Add (this.btnActorsRemove);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnActorsRemove]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.table2.Add (this.hbox1);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox1]));
			w10.TopAttach = ((uint)(10));
			w10.BottomAttach = ((uint)(11));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xpad = 3;
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Episode Start:");
			this.table2.Add (this.label10);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.label10]));
			w11.TopAttach = ((uint)(4));
			w11.BottomAttach = ((uint)(5));
			w11.LeftAttach = ((uint)(2));
			w11.RightAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xpad = 3;
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Directors:");
			this.table2.Add (this.label11);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.label11]));
			w12.TopAttach = ((uint)(6));
			w12.BottomAttach = ((uint)(7));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xpad = 3;
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Writers:");
			this.table2.Add (this.label12);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.label12]));
			w13.TopAttach = ((uint)(7));
			w13.BottomAttach = ((uint)(8));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xpad = 3;
			this.label13.Xalign = 0F;
			this.label13.Yalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Plot:");
			this.table2.Add (this.label13);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.label13]));
			w14.TopAttach = ((uint)(8));
			w14.BottomAttach = ((uint)(9));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xpad = 3;
			this.label14.Xalign = 0F;
			this.label14.Yalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Actors:");
			this.table2.Add (this.label14);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.label14]));
			w15.TopAttach = ((uint)(9));
			w15.BottomAttach = ((uint)(10));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xpad = 3;
			this.label15.Xalign = 0F;
			this.label15.Yalign = 0F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Rating:");
			this.table2.Add (this.label15);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.label15]));
			w16.TopAttach = ((uint)(11));
			w16.BottomAttach = ((uint)(12));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xpad = 3;
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Premiered:");
			this.table2.Add (this.label3);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.LeftAttach = ((uint)(2));
			w17.RightAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xpad = 3;
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Season:");
			this.table2.Add (this.label4);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xpad = 3;
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Display Season:");
			this.table2.Add (this.label5);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xpad = 3;
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Display Episode:");
			this.table2.Add (this.label6);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
			w20.TopAttach = ((uint)(3));
			w20.BottomAttach = ((uint)(4));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xpad = 3;
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Episode:");
			this.table2.Add (this.label7);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.label7]));
			w21.TopAttach = ((uint)(3));
			w21.BottomAttach = ((uint)(4));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xpad = 3;
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("MPAA:");
			this.table2.Add (this.label8);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.label8]));
			w22.TopAttach = ((uint)(4));
			w22.BottomAttach = ((uint)(5));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xpad = 3;
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Studio:");
			this.table2.Add (this.label9);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2 [this.label9]));
			w23.TopAttach = ((uint)(5));
			w23.BottomAttach = ((uint)(6));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.numDisplayEpisode = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.numDisplayEpisode.CanFocus = true;
			this.numDisplayEpisode.Name = "numDisplayEpisode";
			this.numDisplayEpisode.Adjustment.PageIncrement = 10D;
			this.numDisplayEpisode.ClimbRate = 1D;
			this.numDisplayEpisode.Numeric = true;
			this.table2.Add (this.numDisplayEpisode);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2 [this.numDisplayEpisode]));
			w24.TopAttach = ((uint)(3));
			w24.BottomAttach = ((uint)(4));
			w24.LeftAttach = ((uint)(3));
			w24.RightAttach = ((uint)(4));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.numDisplaySeason = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.numDisplaySeason.CanFocus = true;
			this.numDisplaySeason.Name = "numDisplaySeason";
			this.numDisplaySeason.Adjustment.PageIncrement = 10D;
			this.numDisplaySeason.ClimbRate = 1D;
			this.numDisplaySeason.Numeric = true;
			this.table2.Add (this.numDisplaySeason);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2 [this.numDisplaySeason]));
			w25.TopAttach = ((uint)(2));
			w25.BottomAttach = ((uint)(3));
			w25.LeftAttach = ((uint)(3));
			w25.RightAttach = ((uint)(4));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.numEpisode = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.numEpisode.CanFocus = true;
			this.numEpisode.Name = "numEpisode";
			this.numEpisode.Adjustment.PageIncrement = 10D;
			this.numEpisode.ClimbRate = 1D;
			this.numEpisode.Numeric = true;
			this.table2.Add (this.numEpisode);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2 [this.numEpisode]));
			w26.TopAttach = ((uint)(3));
			w26.BottomAttach = ((uint)(4));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.numSeason = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.numSeason.CanFocus = true;
			this.numSeason.Name = "numSeason";
			this.numSeason.Adjustment.PageIncrement = 10D;
			this.numSeason.ClimbRate = 1D;
			this.numSeason.Numeric = true;
			this.table2.Add (this.numSeason);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table2 [this.numSeason]));
			w27.TopAttach = ((uint)(2));
			w27.BottomAttach = ((uint)(3));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.ratingwidget1 = new global::iMetaGui.RatingWidget ();
			this.ratingwidget1.HeightRequest = 15;
			this.ratingwidget1.Events = ((global::Gdk.EventMask)(256));
			this.ratingwidget1.Name = "ratingwidget1";
			this.ratingwidget1.Value = 0;
			this.table2.Add (this.ratingwidget1);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table2 [this.ratingwidget1]));
			w28.TopAttach = ((uint)(11));
			w28.BottomAttach = ((uint)(12));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txtAired = new global::Gtk.Entry ();
			this.txtAired.CanFocus = true;
			this.txtAired.Name = "txtAired";
			this.txtAired.IsEditable = true;
			this.txtAired.InvisibleChar = '●';
			this.table2.Add (this.txtAired);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtAired]));
			w29.TopAttach = ((uint)(1));
			w29.BottomAttach = ((uint)(2));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txtDirectors = new global::Gtk.Entry ();
			this.txtDirectors.CanFocus = true;
			this.txtDirectors.Name = "txtDirectors";
			this.txtDirectors.IsEditable = true;
			this.txtDirectors.InvisibleChar = '●';
			this.table2.Add (this.txtDirectors);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtDirectors]));
			w30.TopAttach = ((uint)(6));
			w30.BottomAttach = ((uint)(7));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(4));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txtEpisodeName = new global::Gtk.Entry ();
			this.txtEpisodeName.CanFocus = true;
			this.txtEpisodeName.Name = "txtEpisodeName";
			this.txtEpisodeName.IsEditable = true;
			this.txtEpisodeName.InvisibleChar = '●';
			this.table2.Add (this.txtEpisodeName);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtEpisodeName]));
			w31.LeftAttach = ((uint)(1));
			w31.RightAttach = ((uint)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txtEpisodeStart = new global::Gtk.Entry ();
			this.txtEpisodeStart.CanFocus = true;
			this.txtEpisodeStart.Name = "txtEpisodeStart";
			this.txtEpisodeStart.IsEditable = true;
			this.txtEpisodeStart.InvisibleChar = '●';
			this.table2.Add (this.txtEpisodeStart);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtEpisodeStart]));
			w32.TopAttach = ((uint)(4));
			w32.BottomAttach = ((uint)(5));
			w32.LeftAttach = ((uint)(3));
			w32.RightAttach = ((uint)(4));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txtMpaa = new global::Gtk.Entry ();
			this.txtMpaa.CanFocus = true;
			this.txtMpaa.Name = "txtMpaa";
			this.txtMpaa.IsEditable = true;
			this.txtMpaa.InvisibleChar = '●';
			this.table2.Add (this.txtMpaa);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtMpaa]));
			w33.TopAttach = ((uint)(4));
			w33.BottomAttach = ((uint)(5));
			w33.LeftAttach = ((uint)(1));
			w33.RightAttach = ((uint)(2));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txtPremiered = new global::Gtk.Entry ();
			this.txtPremiered.CanFocus = true;
			this.txtPremiered.Name = "txtPremiered";
			this.txtPremiered.IsEditable = true;
			this.txtPremiered.InvisibleChar = '●';
			this.table2.Add (this.txtPremiered);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtPremiered]));
			w34.TopAttach = ((uint)(1));
			w34.BottomAttach = ((uint)(2));
			w34.LeftAttach = ((uint)(3));
			w34.RightAttach = ((uint)(4));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txtStudio = new global::Gtk.Entry ();
			this.txtStudio.CanFocus = true;
			this.txtStudio.Name = "txtStudio";
			this.txtStudio.IsEditable = true;
			this.txtStudio.InvisibleChar = '●';
			this.table2.Add (this.txtStudio);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtStudio]));
			w35.TopAttach = ((uint)(5));
			w35.BottomAttach = ((uint)(6));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(4));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txtWriters = new global::Gtk.Entry ();
			this.txtWriters.CanFocus = true;
			this.txtWriters.Name = "txtWriters";
			this.txtWriters.IsEditable = true;
			this.txtWriters.InvisibleChar = '●';
			this.table2.Add (this.txtWriters);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtWriters]));
			w36.TopAttach = ((uint)(7));
			w36.BottomAttach = ((uint)(8));
			w36.LeftAttach = ((uint)(1));
			w36.RightAttach = ((uint)(4));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
