
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow {
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.VBox vboxMovies;
	
	private global::Gtk.Toolbar tlbMovies;
	
	private global::Gtk.ScrolledWindow scrolledwindow1;
	
	private global::Gtk.IconView ivwMovies;
	
	private global::Gtk.Statusbar sbarMovies;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.VBox vboxTvShows;
	
	private global::Gtk.Toolbar toolbar3;
	
	private global::Gtk.ScrolledWindow scrollTvShows;
	
	private global::Gtk.IconView ivwTvShows;
	
	private global::Gtk.Statusbar statusbar2;
	
	private global::Gtk.ProgressBar prgTvShows;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.ScrolledWindow scrolledwindow2;
	
	private global::Gtk.TextView txtLog;
	
	private global::Gtk.Label lblLog;
	
	protected virtual void Build() {
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		this.notebook1.ShowBorder = false;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vboxMovies = new global::Gtk.VBox();
		this.vboxMovies.Name = "vboxMovies";
		this.vboxMovies.Spacing = 6;
		// Container child vboxMovies.Gtk.Box+BoxChild
		this..AddUiFromString("<ui><toolbar name=\'tlbMovies\'><toolitem/><toolitem/><toolitem/><toolitem/><toolit" +
				"em/><toolitem/></toolbar></ui>");
		this.tlbMovies = ((global::Gtk.Toolbar)(this..GetWidget("/tlbMovies")));
		this.tlbMovies.Name = "tlbMovies";
		this.tlbMovies.ShowArrow = false;
		this.tlbMovies.IconSize = ((global::Gtk.IconSize)(4));
		this.vboxMovies.Add(this.tlbMovies);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxMovies[this.tlbMovies]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vboxMovies.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.ivwMovies = new global::Gtk.IconView();
		this.ivwMovies.CanFocus = true;
		this.ivwMovies.Name = "ivwMovies";
		this.scrolledwindow1.Add(this.ivwMovies);
		this.vboxMovies.Add(this.scrolledwindow1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMovies[this.scrolledwindow1]));
		w3.Position = 1;
		// Container child vboxMovies.Gtk.Box+BoxChild
		this.sbarMovies = new global::Gtk.Statusbar();
		this.sbarMovies.Name = "sbarMovies";
		this.sbarMovies.Spacing = 6;
		this.vboxMovies.Add(this.sbarMovies);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxMovies[this.sbarMovies]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.notebook1.Add(this.vboxMovies);
		// Notebook tab
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Movies");
		this.notebook1.SetTabLabel(this.vboxMovies, this.label1);
		this.label1.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vboxTvShows = new global::Gtk.VBox();
		this.vboxTvShows.Name = "vboxTvShows";
		// Container child vboxTvShows.Gtk.Box+BoxChild
		this..AddUiFromString("<ui><toolbar name=\'toolbar3\'><toolitem/><toolitem/><toolitem/></toolbar></ui>");
		this.toolbar3 = ((global::Gtk.Toolbar)(this..GetWidget("/toolbar3")));
		this.toolbar3.Name = "toolbar3";
		this.toolbar3.ShowArrow = false;
		this.vboxTvShows.Add(this.toolbar3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vboxTvShows[this.toolbar3]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vboxTvShows.Gtk.Box+BoxChild
		this.scrollTvShows = new global::Gtk.ScrolledWindow();
		this.scrollTvShows.CanFocus = true;
		this.scrollTvShows.Name = "scrollTvShows";
		this.scrollTvShows.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrollTvShows.Gtk.Container+ContainerChild
		this.ivwTvShows = new global::Gtk.IconView();
		this.ivwTvShows.CanFocus = true;
		this.ivwTvShows.Name = "ivwTvShows";
		this.scrollTvShows.Add(this.ivwTvShows);
		this.vboxTvShows.Add(this.scrollTvShows);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxTvShows[this.scrollTvShows]));
		w8.Position = 1;
		// Container child vboxTvShows.Gtk.Box+BoxChild
		this.statusbar2 = new global::Gtk.Statusbar();
		this.statusbar2.Name = "statusbar2";
		this.statusbar2.Spacing = 2;
		// Container child statusbar2.Gtk.Box+BoxChild
		this.prgTvShows = new global::Gtk.ProgressBar();
		this.prgTvShows.Name = "prgTvShows";
		this.statusbar2.Add(this.prgTvShows);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.statusbar2[this.prgTvShows]));
		w9.Position = 2;
		this.vboxTvShows.Add(this.statusbar2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxTvShows[this.statusbar2]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.notebook1.Add(this.vboxTvShows);
		global::Gtk.Notebook.NotebookChild w11 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vboxTvShows]));
		w11.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("TV Shows");
		this.notebook1.SetTabLabel(this.vboxTvShows, this.label2);
		this.label2.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow2.CanFocus = true;
		this.scrolledwindow2.Name = "scrolledwindow2";
		this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow2.Gtk.Container+ContainerChild
		this.txtLog = new global::Gtk.TextView();
		this.txtLog.CanFocus = true;
		this.txtLog.Name = "txtLog";
		this.scrolledwindow2.Add(this.txtLog);
		this.notebook1.Add(this.scrolledwindow2);
		global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.scrolledwindow2]));
		w13.Position = 2;
		// Notebook tab
		this.lblLog = new global::Gtk.Label();
		this.lblLog.Name = "lblLog";
		this.lblLog.LabelProp = global::Mono.Unix.Catalog.GetString("page3");
		this.notebook1.SetTabLabel(this.scrolledwindow2, this.lblLog);
		this.lblLog.ShowAll();
		this.Add(this.notebook1);
		if ((this.Child != null)) {
			this.Child.ShowAll();
		}
		this.DefaultWidth = 867;
		this.DefaultHeight = 542;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
